# Generated by Django 3.1.6 on 2021-02-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyNode',
            fields=[
                ('taxon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ncbi_taxonomy.taxonomynode')),
                ('rank', models.CharField(max_length=32)),
                ('genbank_hidden_flag', models.IntegerField()),
                ('left_index', models.IntegerField()),
                ('right_index', models.IntegerField()),
                ('root_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ncbi_taxa_node',
                'managed': True,
                'verbose_name': 'Taxon'
            },
        ),
        migrations.CreateModel(
            name='TaxonomyName',
            fields=[
                ('name_id', models.AutoField(primary_key=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncbi_taxonomy.taxonomynode')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_class', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ncbi_taxa_name',
                'managed': True,
                'unique_together': {('taxon_id', 'name', 'name_class')},
                'verbose_name': 'Taxon name'
            },
        ),
    ]
