# Generated by Django 3.1.6 on 2021-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='genebuild',
            field=models.CharField(max_length=255),
        ),
    ]
