# Generated by Django 3.1.7 on 2021-03-25 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_uuid', models.CharField(default=uuid.uuid1, max_length=128, unique=True)),
                ('type', models.CharField(choices=[('assembly', 'Assembly'), ('xrefs', 'Cross References'), ('dna_alignments', 'Dna Alignments'), ('geneset', 'Geneset'), ('gene_families', 'Gene Families'), ('gene_trees', 'Gene Trees'), ('genome_alignments', 'Genome Alignments'), ('go_terms', 'Go Terms'), ('homologies', 'Homologies'), ('microarrays', 'Microarrays'), ('phenotypes', 'Phenotypes'), ('protein_alignments', 'Protein Alignments'), ('protein_features', 'Protein Features'), ('repeat_features', 'Repeat Features'), ('rnaseq_alignments', 'Rnaseq Alignments'), ('syntenies', 'Syntenies'), ('variants', 'Variants')], max_length=32)),
                ('name', models.CharField(max_length=128, null=True)),
                ('version', models.CharField(max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='DatasetDatabase',
            fields=[
                ('dataset_database_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('core', 'Core'), ('cdna', 'Cdna'), ('otherfeatures', 'Otherfeatures'), ('rnaseq', 'Rnaseq'), ('compara', 'Compara'), ('funcgen', 'Funcgen'), ('variation', 'Variation')], max_length=32)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'dataset_database',
            },
        ),
        migrations.CreateModel(
            name='DatasetStatistic',
            fields=[
                ('dataset_statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='ensembl_metadata.dataset')),
            ],
            options={
                'db_table': 'dataset_statistic',
                'unique_together': {('dataset', 'type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OrganismGroupMember',
            fields=[
                ('organism_group_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_reference', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organism_group_member',
            },
        ),
        migrations.AlterUniqueTogether(
            name='comparaanalysis',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='comparaanalysis',
            name='data_release',
        ),
        migrations.RemoveField(
            model_name='comparaanalysis',
            name='division',
        ),
        migrations.RemoveField(
            model_name='comparaanalysis',
            name='genome_compara_analysis',
        ),
        migrations.RemoveField(
            model_name='comparaanalysisevent',
            name='compara_analysis',
        ),
        migrations.RemoveField(
            model_name='datarelease',
            name='site',
        ),
        migrations.AlterUniqueTogether(
            name='genomealignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomealignment',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genomealignment',
            name='genome_database',
        ),
        migrations.AlterUniqueTogether(
            name='genomeannotation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomeannotation',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genomeannotation',
            name='genome_database',
        ),
        migrations.AlterUniqueTogether(
            name='genomecomparaanalysis',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomecomparaanalysis',
            name='compara_analysis',
        ),
        migrations.RemoveField(
            model_name='genomecomparaanalysis',
            name='genome',
        ),
        migrations.AlterUniqueTogether(
            name='genomedatabase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomedatabase',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genomedivision',
            name='division',
        ),
        migrations.RemoveField(
            model_name='genomedivision',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genomeevent',
            name='genome',
        ),
        migrations.AlterUniqueTogether(
            name='genomefeature',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomefeature',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genomefeature',
            name='genome_database',
        ),
        migrations.AlterUniqueTogether(
            name='genomevariation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomevariation',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='genomevariation',
            name='genome_database',
        ),
        migrations.AlterUniqueTogether(
            name='organismalias',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organismalias',
            name='organism',
        ),
        migrations.AlterUniqueTogether(
            name='organismpublication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organismpublication',
            name='organism',
        ),
        migrations.AlterModelOptions(
            name='assembly',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assemblysequence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genome',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genomerelease',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organism',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organismgroup',
            options={},
        ),
        migrations.RenameField(
            model_name='assembly',
            old_name='assembly_ucsc',
            new_name='ucsc_name',
        ),
        migrations.RenameField(
            model_name='organismgroup',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organismgroup',
            old_name='group_id',
            new_name='organism_group_id',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='created',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='genebuild',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='has_genome_alignments',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='has_microarray',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='has_other_alignments',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='has_pan_compara',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='has_peptide_compara',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='has_synteny',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='has_variation',
        ),
        migrations.RemoveField(
            model_name='genomerelease',
            name='data_release',
        ),
        migrations.RemoveField(
            model_name='genomerelease',
            name='division',
        ),
        migrations.RemoveField(
            model_name='genomerelease',
            name='genome_uuid',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='group',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='image',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='serotype',
        ),
        migrations.AddField(
            model_name='assembly',
            name='accession',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='level',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='assembly',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='assemblysequence',
            name='accession',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assemblysequence',
            name='chromosomal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assemblysequence',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='assemblysequence',
            name='sequence_location',
            field=models.CharField(default='SO:0000738', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='genomerelease',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='ensembl_metadata.genome'),
        ),
        migrations.AddField(
            model_name='organism',
            name='ensembl_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='assemblysequence',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='ensembl_metadata.assembly'),
        ),
        migrations.AlterField(
            model_name='assemblysequence',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='genome',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='ensembl_metadata.assembly'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='genome_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genome',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='ensembl_metadata.organism'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='species_taxonomy_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organismgroup',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assembly',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assemblysequence',
            unique_together={('assembly', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='organismgroup',
            unique_together={('type', 'name')},
        ),
        migrations.AlterModelTable(
            name='organismgroup',
            table='organism_group',
        ),
        migrations.DeleteModel(
            name='AssemblyKaryotype',
        ),
        migrations.DeleteModel(
            name='ComparaAnalysis',
        ),
        migrations.DeleteModel(
            name='ComparaAnalysisEvent',
        ),
        migrations.DeleteModel(
            name='DataRelease',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='EnsemblSite',
        ),
        migrations.DeleteModel(
            name='GenomeAlignment',
        ),
        migrations.DeleteModel(
            name='GenomeAnnotation',
        ),
        migrations.DeleteModel(
            name='GenomeComparaAnalysis',
        ),
        migrations.DeleteModel(
            name='GenomeDatabase',
        ),
        migrations.DeleteModel(
            name='GenomeDivision',
        ),
        migrations.DeleteModel(
            name='GenomeEvent',
        ),
        migrations.DeleteModel(
            name='GenomeFeature',
        ),
        migrations.DeleteModel(
            name='GenomeVariation',
        ),
        migrations.DeleteModel(
            name='OrganismAlias',
        ),
        migrations.DeleteModel(
            name='OrganismPublication',
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('release_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('release_date', models.DateField()),
                ('label', models.CharField(max_length=64, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ensembl_release',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=64)),
                ('uri', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'ensembl_site',
            },
        ),
        migrations.AddField(
            model_name='release',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='ensembl_metadata.site'),
        ),
        migrations.AddField(
            model_name='organismgroupmember',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ensembl_metadata.organism'),
        ),
        migrations.AddField(
            model_name='organismgroupmember',
            name='organism_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ensembl_metadata.organismgroup'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='ensembl_metadata.datasetdatabase'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='ensembl_metadata.genome'),
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_accession',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_default',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_level',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_name',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='base_count',
        ),
        migrations.RemoveField(
            model_name='assemblysequence',
            name='acc',
        ),
        migrations.RemoveField(
            model_name='organismgroup',
            name='reference_organism',
        ),
        migrations.AddField(
            model_name='genomerelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='ensembl_metadata.release'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('version', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='organismgroupmember',
            unique_together={('organism', 'organism_group')},
        ),
    ]
