# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-10 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='genebuild',
            field=models.CharField(max_length=255),
        ),
    ]
