# Generated by Django 3.1.7 on 2021-03-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0002_auto_20210325_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='genome',
        ),
        migrations.CreateModel(
            name='GenomeDataset',
            fields=[
                ('genome_dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='ensembl_metadata.dataset')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='ensembl_metadata.genome')),
            ],
        ),
    ]
