# Generated by Django 3.1.6 on 2021-03-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0002_auto_20210210_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblykaryotype',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karyotypes', to='ensembl_metadata.assembly'),
        ),
        migrations.AlterField(
            model_name='assemblysequence',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='ensembl_metadata.assembly'),
        ),
        migrations.AlterField(
            model_name='comparaanalysis',
            name='data_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ensembl_metadata.datarelease'),
        ),
        migrations.AlterField(
            model_name='comparaanalysis',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ensembl_metadata.division'),
        ),
        migrations.AlterField(
            model_name='comparaanalysis',
            name='genome_compara_analysis',
            field=models.ManyToManyField(through='ensembl_metadata.GenomeComparaAnalysis', to='ensembl_metadata.Genome'),
        ),
        migrations.AlterField(
            model_name='comparaanalysisevent',
            name='compara_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ensembl_metadata.comparaanalysis'),
        ),
        migrations.AlterField(
            model_name='datarelease',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_releases', to='ensembl_metadata.ensemblsite'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='ensembl_metadata.assembly'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='ensembl_metadata.organism'),
        ),
        migrations.AlterField(
            model_name='genomealignment',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='ensembl_metadata.genome'),
        ),
        migrations.AlterField(
            model_name='genomealignment',
            name='genome_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='ensembl_metadata.genomedatabase'),
        ),
        migrations.AlterField(
            model_name='genomeannotation',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='ensembl_metadata.genome'),
        ),
        migrations.AlterField(
            model_name='genomeannotation',
            name='genome_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='ensembl_metadata.genomedatabase'),
        ),
        migrations.AlterField(
            model_name='genomecomparaanalysis',
            name='compara_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ensembl_metadata.comparaanalysis'),
        ),
        migrations.AlterField(
            model_name='genomecomparaanalysis',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ensembl_metadata.genome'),
        ),
        migrations.AlterField(
            model_name='genomedatabase',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='ensembl_metadata.genome'),
        ),
        migrations.AlterField(
            model_name='genomedivision',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='ensembl_metadata.division'),
        ),
        migrations.AlterField(
            model_name='genomedivision',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='ensembl_metadata.genome'),
        ),
        migrations.AlterField(
            model_name='genomeevent',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ensembl_metadata.genome'),
        ),
        migrations.AlterField(
            model_name='genomefeature',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ensembl_metadata.genome'),
        ),
        migrations.AlterField(
            model_name='genomefeature',
            name='genome_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ensembl_metadata.genomedatabase'),
        ),
        migrations.AlterField(
            model_name='genomerelease',
            name='data_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='ensembl_metadata.datarelease'),
        ),
        migrations.AlterField(
            model_name='genomerelease',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='ensembl_metadata.division'),
        ),
        migrations.AlterField(
            model_name='genomerelease',
            name='genome_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='ensembl_metadata.genome', to_field='genome_uuid'),
        ),
        migrations.AlterField(
            model_name='genomevariation',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='ensembl_metadata.genome'),
        ),
        migrations.AlterField(
            model_name='genomevariation',
            name='genome_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='ensembl_metadata.genomedatabase'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisms', to='ensembl_metadata.organismgroup'),
        ),
        migrations.AlterField(
            model_name='organismalias',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ensembl_metadata.organism'),
        ),
        migrations.AlterField(
            model_name='organismpublication',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='ensembl_metadata.organism'),
        ),
        migrations.AlterUniqueTogether(
            name='assembly',
            unique_together=set(),
        ),
    ]
