# Generated by Django 3.1.7 on 2021-04-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0003_auto_20210325_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSource',
            fields=[
                ('dataset_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('core', 'Core'), ('cdna', 'Cdna'), ('datafile', 'Datafile'), ('otherfeatures', 'Otherfeatures'), ('rnaseq', 'Rnaseq'), ('compara', 'Compara'), ('funcgen', 'Funcgen'), ('variation', 'Variation')], max_length=32)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'dataset_source',
            },
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_database',
        ),
        migrations.RemoveField(
            model_name='genomedataset',
            name='is_current',
        ),
        migrations.AddField(
            model_name='genomedataset',
            name='release',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='genome_datasets', to='ensembl_metadata.release'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='genomedataset',
            table='genome_dataset',
        ),
        migrations.DeleteModel(
            name='DatasetDatabase',
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='ensembl_metadata.datasetsource'),
            preserve_default=False,
        ),
    ]
