# Generated by Django 3.1.6 on 2021-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0003_auto_20210310_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnsemblSite',
            new_name='Site',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='image',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='serotype',
        ),
        migrations.AlterField(
            model_name='organism',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='datarelease',
            unique_together={('version', 'site')},
        ),
        migrations.DeleteModel(
            name='OrganismPublication',
        ),
    ]
