# Generated by Django 3.1.7 on 2021-04-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0003_auto_20210325_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_database',
        ),
        migrations.RemoveField(
            model_name='genomedataset',
            name='is_current',
        ),
        migrations.AddField(
            model_name='genomedataset',
            name='dataset_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_datasets', to='ensembl_metadata.datasetdatabase'),
        ),
        migrations.AddField(
            model_name='genomedataset',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_datasets', to='ensembl_metadata.release'),
        ),
    ]
