# Generated by Django 3.1.7 on 2021-04-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0004_auto_20210412_1738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genomedataset',
            table='genome_dataset',
        ),
    ]
