# Generated by Django 3.1.7 on 2021-04-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0004_auto_20210413_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetType',
            fields=[
                ('dataset_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=32)),
                ('topic', models.CharField(choices=[('assembly', 'Assembly'), ('geneset', 'Geneset'), ('assembly_annotation', 'Assembly Annotation'), ('geneset_annotation', 'Geneset Annotation'), ('comparative', 'Comparative'), ('regulation', 'Regulation'), ('variation', 'Variation')], max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('details_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dataset_type',
            },
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organismgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organismgroup',
            name='type',
            field=models.CharField(choices=[('breeds', 'Breeds'), ('cultivars', 'Cultivars'), ('division', 'Division'), ('populations', 'Populations'), ('strains', 'Strains')], max_length=32),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='ensembl_metadata.datasettype'),
        ),
    ]
