# Generated by Django 3.1.7 on 2021-04-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0005_auto_20210415_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='type',
            new_name='dataset_type',
        ),
    ]
