# Generated by Django 3.1.6 on 2021-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0006_auto_20210313_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='species_taxonomy_id',
            field=models.IntegerField(null=True),
        ),
    ]
