# Generated by Django 3.1.6 on 2021-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0007_auto_20210313_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='label',
            field=models.CharField(default='x', max_length=64),
            preserve_default=False,
        ),
    ]
