# Generated by Django 3.1.6 on 2021-03-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0008_site_label'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='release',
            table='ensembl_release',
        ),
    ]
