# Generated by Django 3.1.6 on 2021-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0010_auto_20210313_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='genome_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
