# Generated by Django 3.1.6 on 2021-03-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0011_auto_20210313_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
