# Generated by Django 3.1.6 on 2021-03-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0012_auto_20210313_2153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='ensembl_site',
        ),
    ]
