# Generated by Django 3.1.6 on 2021-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0013_auto_20210314_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.CharField(choices=[('assembly', 'Assembly'), ('xrefs', 'Cross References'), ('dna_alignments', 'Dna Alignments'), ('geneset', 'Geneset'), ('gene_families', 'Gene Families'), ('gene_trees', 'Gene Trees'), ('genome_alignments', 'Genome Alignments'), ('homology', 'Homology'), ('microarrays', 'Microarrays'), ('phenotypes', 'Phenotypes'), ('protein_alignments', 'Protein Alignments'), ('protein_features', 'Protein Features'), ('repeat_features', 'Repeat Features'), ('rnaseq_alignments', 'Rnaseq Alignments'), ('synteny', 'Synteny'), ('variants', 'Variants')], max_length=32),
        ),
    ]
