# Generated by Django 3.1.6 on 2021-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0014_auto_20210314_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdatabase',
            name='type',
            field=models.CharField(choices=[('core', 'Core'), ('cdna', 'Cdna'), ('otherfeatures', 'Otherfeatures'), ('rnaseq', 'Rnaseq'), ('compara', 'Compara'), ('funcgen', 'Funcgen'), ('variation', 'Variation')], default='core', max_length=32),
            preserve_default=False,
        ),
    ]
