# Generated by Django 3.1.6 on 2021-03-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0015_auto_20210314_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenomeAttribute',
        ),
    ]
