# Generated by Django 3.1.6 on 2021-03-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0017_auto_20210315_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='base_count',
        ),
    ]
