# Generated by Django 3.1.6 on 2021-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0018_remove_assembly_base_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='accession',
            field=models.CharField(default='x', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
