# Generated by Django 3.1.7 on 2021-03-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0019_auto_20210316_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assemblysequence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bundle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datasetdatabase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datasetrelease',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datasetstatistic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genome',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genomebundle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
        migrations.AlterModelTable(
            name='assembly',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assemblysequence',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bundle',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dataset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='datasetdatabase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='datasetrelease',
            table=None,
        ),
        migrations.AlterModelTable(
            name='datasetstatistic',
            table=None,
        ),
        migrations.AlterModelTable(
            name='genome',
            table=None,
        ),
        migrations.AlterModelTable(
            name='genomebundle',
            table=None,
        ),
    ]
