# Generated by Django 3.1.7 on 2021-03-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0020_auto_20210317_1116'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assembly',
            table='assembly',
        ),
        migrations.AlterModelTable(
            name='assemblysequence',
            table='assembly_sequence',
        ),
        migrations.AlterModelTable(
            name='bundle',
            table='bundle',
        ),
        migrations.AlterModelTable(
            name='dataset',
            table='dataset',
        ),
        migrations.AlterModelTable(
            name='datasetdatabase',
            table='dataset_database',
        ),
        migrations.AlterModelTable(
            name='datasetrelease',
            table='dataset_release',
        ),
        migrations.AlterModelTable(
            name='datasetstatistic',
            table='dataset_statistic',
        ),
        migrations.AlterModelTable(
            name='genome',
            table='genome',
        ),
        migrations.AlterModelTable(
            name='genomebundle',
            table='genome_bundle',
        ),
    ]
