# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-07 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(blank=True, null=True, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_organism', models.ForeignKey(db_column='reference_organism_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_in_groups', to='metadata_registry.Organism')),
            ],
            options={
                'db_table': 'group',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='organism',
            name='group',
            field=models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_in_organims', to='metadata_registry.Group'),
        ),
    ]
