# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-10 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_organism', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_groups', to='metadata_registry.Organism')),
            ],
            options={
                'db_table': 'group',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='organism',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_organisms', to='metadata_registry.OrganismGroup'),
        ),
    ]
