# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-15 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_registry', '0002_organism_group_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyKaryotype',
            fields=[
                ('assembly_karyotype_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=40)),
                ('region_start', models.IntegerField()),
                ('region_end', models.IntegerField()),
                ('band', models.CharField(max_length=50)),
                ('strain', models.CharField(max_length=50)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assembly_sequence', to='metadata_registry.Assembly')),
            ],
            options={
                'db_table': 'assembly_karyotype',
                'managed': True,
            },
        ),
    ]
