# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_registry', '0003_assembly_karyotype_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsemblSite',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('uri', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'ensembl_site',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='datarelease',
            old_name='ensembl_version',
            new_name='version',
        ),
        migrations.AddField(
            model_name='datarelease',
            name='label',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='datarelease',
            unique_together=set([]),
        ),
        migrations.AlterModelTable(
            name='datarelease',
            table='ensembl_release',
        ),
        migrations.RemoveField(
            model_name='datarelease',
            name='ensembl_genomes_version',
        ),
        migrations.AddField(
            model_name='datarelease',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_id_release', to='metadata_registry.EnsemblSite'),
        ),
        migrations.RemoveField(
            model_name='datareleasedatabase',
            name='data_release',
        ),
        migrations.RemoveField(
            model_name='datareleasedatabaseevent',
            name='data_release_database',
        ),
        migrations.DeleteModel(
            name='DataReleaseDatabase',
        ),
        migrations.DeleteModel(
            name='DataReleaseDatabaseEvent',
        ),
    ]
