# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_registry', '0005_data_release_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeBest',
            fields=[
                ('common_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'genome_best',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GenomeRelease',
            fields=[
                ('genome_release_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_registry.DataRelease')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_registry.Division')),
            ],
            options={
                'db_table': 'genome_release',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='has_variations',
            new_name='has_variation',
        ),
        migrations.AddField(
            model_name='genome',
            name='genome_uuid',
            field=models.CharField(default=uuid.uuid1, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='has_microarray',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genomerelease',
            name='genome_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_registry.Genome'),
        ),
        migrations.AddField(
            model_name='genomebest',
            name='genome_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_registry.Genome'),
        ),
        migrations.RemoveField(
            model_name='genome',
            name='data_release',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='division',
        ),
    ]
