# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_registry', '0005_genome_info_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblykaryotype',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_sequence', to='metadata_registry.Assembly'),
        ),
        migrations.AlterField(
            model_name='assemblysequence',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_sequence', to='metadata_registry.Assembly'),
        ),
        migrations.AlterField(
            model_name='comparaanalysis',
            name='data_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_release_compara', to='metadata_registry.DataRelease'),
        ),
        migrations.AlterField(
            model_name='comparaanalysis',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_compara', to='metadata_registry.Division'),
        ),
        migrations.AlterField(
            model_name='comparaanalysisevent',
            name='compara_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_registry.ComparaAnalysis'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly', to='metadata_registry.Assembly'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='metadata_registry.Organism'),
        ),
        migrations.AlterField(
            model_name='genomealignment',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_alignment', to='metadata_registry.Genome'),
        ),
        migrations.AlterField(
            model_name='genomealignment',
            name='genome_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_alignment', to='metadata_registry.GenomeDatabase'),
        ),
        migrations.AlterField(
            model_name='genomeannotation',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_annotation', to='metadata_registry.Genome'),
        ),
        migrations.AlterField(
            model_name='genomeannotation',
            name='genome_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_annotation', to='metadata_registry.GenomeDatabase'),
        ),
        migrations.AlterField(
            model_name='genomecomparaanalysis',
            name='compara_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_registry.ComparaAnalysis'),
        ),
        migrations.AlterField(
            model_name='genomecomparaanalysis',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata_registry.Genome'),
        ),
        migrations.AlterField(
            model_name='genomedatabase',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_database', to='metadata_registry.Genome'),
        ),
        migrations.AlterField(
            model_name='genomeevent',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_event', to='metadata_registry.Genome'),
        ),
        migrations.AlterField(
            model_name='genomefeature',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_feature', to='metadata_registry.Genome'),
        ),
        migrations.AlterField(
            model_name='genomefeature',
            name='genome_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_feature', to='metadata_registry.GenomeDatabase'),
        ),
        migrations.AlterField(
            model_name='genomevariation',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_variation', to='metadata_registry.Genome'),
        ),
        migrations.AlterField(
            model_name='genomevariation',
            name='genome_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_variation', to='metadata_registry.GenomeDatabase'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_organisms', to='metadata_registry.OrganismGroup'),
        ),
        migrations.AlterField(
            model_name='organismalias',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism_alias', to='metadata_registry.Organism'),
        ),
        migrations.AlterField(
            model_name='organismpublication',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism_publication', to='metadata_registry.Organism'),
        ),
        migrations.AlterUniqueTogether(
            name='genome',
            unique_together=set([]),
        ),
        migrations.AlterField(
            model_name='datarelease',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_id_release', to='metadata_registry.EnsemblSite'),
        ),
    ]
