# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-05 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_registry', '0006_delete_cascade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genomebest',
            name='genome_uuid',
        ),
        migrations.DeleteModel(
            name='GenomeBest',
        ),
    ]
